//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_sem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Device_PropertyEntities : DbContext
    {
        public Device_PropertyEntities()
            : base("name=Device_PropertyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Laptops> Laptops { get; set; }
        public virtual DbSet<PropertyType> PropertyType { get; set; }
        public virtual DbSet<PropertyValue> PropertyValue { get; set; }
        public virtual DbSet<PropertyValueToLaptops> PropertyValueToLaptops { get; set; }
        public virtual DbSet<ListSite> ListSite { get; set; }
        public virtual DbSet<Phones> Phones { get; set; }
        public virtual DbSet<PropertyTypePhones> PropertyTypePhones { get; set; }
        public virtual DbSet<PropertyValuePhones> PropertyValuePhones { get; set; }
        public virtual DbSet<PropertyValueToPhones> PropertyValueToPhones { get; set; }
        public virtual DbSet<ListSitePhones> ListSitePhones { get; set; }
    }
}
