//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_sem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListSitePhones
    {
        public long ID { get; set; }
        public string site { get; set; }
        public Nullable<bool> IsUsing { get; set; }
        public string TotalResult { get; set; }
        public string LastDeviceId { get; set; }
    }
}
