//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_sem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phones()
        {
            this.PropertyValueToPhones = new HashSet<PropertyValueToPhones>();
        }
    
        public long ID { get; set; }
        public string sem3_id { get; set; }
        public string upc { get; set; }
        public string ean { get; set; }
        public string gtinsArray { get; set; }
        public string cat_id { get; set; }
        public string Category { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string mpn { get; set; }
        public string Series { get; set; }
        public string Physical_width { get; set; }
        public string Physical_length { get; set; }
        public string Physical_height { get; set; }
        public string Color { get; set; }
        public string Weight { get; set; }
        public string variation_id { get; set; }
        public string variation_id_Array { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyValueToPhones> PropertyValueToPhones { get; set; }
    }
}
