//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_sem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyValue()
        {
            this.PropertyValueToLaptops = new HashSet<PropertyValueToLaptops>();
        }
    
        public long ID { get; set; }
        public string Value { get; set; }
        public Nullable<long> PTid { get; set; }
    
        public virtual PropertyType PropertyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyValueToLaptops> PropertyValueToLaptops { get; set; }
    }
}
