//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_sem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyValueToPhones
    {
        public long ID { get; set; }
        public Nullable<long> PhoneId { get; set; }
        public Nullable<long> PVId { get; set; }
    
        public virtual Phones Phones { get; set; }
        public virtual PropertyValuePhones PropertyValuePhones { get; set; }
    }
}
